version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      POSTGRES_CONNECTION_STRING: postgres://postgres:secret@db/postgres
      NODE_ENV: development
    ports:
      - 3000:3000
    links:
      - db
    volumes:
      - ./:/usr/src/app/
